### ISSUE TITLE
a warning message for jdk11 build with redission

### ISSUE THREAD

**Issue by stevehu** [networknt/light-session-4j#21]
```
WARNING: Illegal reflective access by com.thoughtworks.xstream.core.util.Fields (file:/home/steve/.m2/repository/com/thoughtworks/xstream/xstream/1.4.7/xstream-1.4.7.jar) to field java.util.TreeMap.comparator
WARNING: Please consider reporting this to the maintainers of com.thoughtworks.xstream.core.util.Fields
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
java.io.IOException: java.lang.NoSuchMethodException: java.net.URI.lowMask(java.lang.String)
	at org.redisson.config.ConfigSupport.patchUriField(ConfigSupport.java:148)
	at org.redisson.config.ConfigSupport.patchUriObject(ConfigSupport.java:128)
	at org.redisson.config.ConfigSupport.fromJSON(ConfigSupport.java:179)
	at org.redisson.config.Config.fromJSON(Config.java:627)
	at com.networknt.session.redis.RedisSessionRepository.<clinit>(RedisSessionRepository.java:50)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at com.networknt.service.SingletonServiceFactory.handleSingleImpl(SingletonServiceFactory.java:72)
	at com.networknt.service.SingletonServiceFactory.handleSingletonList(SingletonServiceFactory.java:221)
	at com.networknt.service.SingletonServiceFactory.<clinit>(SingletonServiceFactory.java:56)
	at com.networknt.session.redis.RedisSessionSingleIT.lambda$getTestHandler$0(RedisSessionSingleIT.java:63)
	at io.undertow.server.RoutingHandler.handleRequest(RoutingHandler.java:93)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:364)
	at io.undertow.server.protocol.http.HttpReadListener.handleEventWithNoRunningRequest(HttpReadListener.java:255)
	at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:136)
	at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:59)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.conduits.ReadReadyHandler$ChannelListenerHandler.readReady(ReadReadyHandler.java:66)
	at org.xnio.nio.NioSocketConduit.handleReady(NioSocketConduit.java:88)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:561)
Caused by: java.lang.NoSuchMethodException: java.net.URI.lowMask(java.lang.String)
	at java.base/java.lang.Class.getDeclaredMethod(Class.java:2475)
	at org.redisson.config.ConfigSupport.patchUriField(ConfigSupport.java:135)
	... 19 more

```

**Comment by stevehu** [comment]
This issue is gone after upgrading to the latest version of the Redis lib.
